export type WeeklyAction = {t: string; dur: string; desc: string};

export const WA: Record<string, {t: string; dur: string; desc: string}[][]> = {
  "sleep": [
    [{t:"Set a fixed wake-up time",dur:"All day",desc:"Choose one wake-up time and stick to it, even on weekends. Consistency trains your circadian rhythm."},
     {t:"Track your sleep window",dur:"5 min",desc:"Record what time you got in bed, when you fell asleep, and when you woke up."},
     {t:"Rate your morning energy",dur:"2 min",desc:"Score 1-10 how rested you feel. Note any patterns with yesterday's habits."},
     {t:"Identify one sleep disruptor",dur:"5 min",desc:"Write down the biggest thing hurting your sleep: screens, caffeine, stress, or noise."}],
    [{t:"10-minute morning sunlight",dur:"10 min",desc:"Get direct sunlight within 30 minutes of waking. Step outside, no sunglasses. Sets your cortisol peak."},
     {t:"Set a fixed wake-up time",dur:"All day",desc:"Same time every day. Your body clock needs at least a week of consistency to lock in."},
     {t:"Delay caffeine 90 minutes",dur:"All day",desc:"Wait 90 minutes after waking for your first coffee. Let cortisol peak naturally first."},
     {t:"Journal: energy patterns",dur:"5 min",desc:"Note when you felt most alert and most tired today. Look for your natural rhythm."}],
    [{t:"No screens 45 min before bed",dur:"45 min",desc:"Put your phone in another room. Use this time for reading, stretching, or journaling."},
     {t:"Design a wind-down ritual",dur:"15 min",desc:"Create a 3-step pre-sleep routine: dim lights, light stretching, and a calming activity."},
     {t:"10-minute morning sunlight",dur:"10 min",desc:"Continue the morning light habit. It compounds over time."},
     {t:"Set bedroom to 65-68°F",dur:"2 min",desc:"Cool rooms promote deeper sleep. Adjust thermostat or use lighter blankets."}],
    [{t:"Set bedroom to 65-68°F",dur:"2 min",desc:"Cool environments signal your body to produce melatonin. Aim for 65-68 degrees."},
     {t:"No food 3 hours before bed",dur:"All day",desc:"Late eating raises core body temperature and disrupts sleep architecture."},
     {t:"Try a warm shower before bed",dur:"10 min",desc:"A warm shower 60-90 minutes before bed drops core temperature when you get out, triggering sleepiness."},
     {t:"Rate your sleep quality",dur:"2 min",desc:"Score last night 1-10. Note if temperature changes made a difference."}],
    [{t:"Set a fixed wake-up time",dur:"All day",desc:"By week 5, this should feel automatic. If you are still struggling, your bedtime may be too late."},
     {t:"No screens 45 min before bed",dur:"45 min",desc:"Continue this boundary. Notice how your wind-down time feels more natural now."},
     {t:"Weekend consistency check",dur:"5 min",desc:"Plan your weekend wake time. Sleeping in more than 30 minutes disrupts your clock."},
     {t:"Journal: sleep reflection",dur:"5 min",desc:"Write what has changed since week 1. Which habits stuck? Which need work?"}],
    [{t:"Full evening routine",dur:"15 min",desc:"Run your complete wind-down ritual: screens off, dim lights, stretching, cool room."},
     {t:"Audit your sleep environment",dur:"10 min",desc:"Check for light leaks, noise sources, and temperature. Make one final optimization."},
     {t:"Plan for disruptions",dur:"5 min",desc:"Write a plan for nights when routine breaks: travel, social events, stress. How will you recover?"},
     {t:"Celebrate your progress",dur:"5 min",desc:"Review your sleep scores from week 1 vs now. Acknowledge the improvement."}],
  ],
  "strength": [
    [{t:"Movement assessment",dur:"15 min",desc:"Test your squat depth, push-up form, and hip hinge. Record what feels stiff or weak."},
     {t:"Set training schedule",dur:"10 min",desc:"Block 3 days this week in your calendar for 30-minute sessions. Consistency beats intensity."},
     {t:"Learn the hip hinge",dur:"15 min",desc:"Practice the Romanian deadlift pattern with no weight. Hinge at hips, flat back, feel hamstrings stretch."},
     {t:"10-minute mobility work",dur:"10 min",desc:"Foam roll quads, hip flexors, and upper back. Do 90/90 hip stretch each side."}],
    [{t:"Push workout: push-ups and press",dur:"30 min",desc:"3 sets of push-ups to near failure. 3 sets of overhead press with light dumbbells."},
     {t:"Pull workout: rows and curls",dur:"30 min",desc:"3 sets of dumbbell rows each side. 3 sets of band pull-aparts. 2 sets of curls."},
     {t:"Track your reps",dur:"5 min",desc:"Write down sets, reps, and weight for every exercise. Progress requires measurement."},
     {t:"Post-workout stretching",dur:"10 min",desc:"Stretch chest, lats, hip flexors, and hamstrings. Hold each 30 seconds."}],
    [{t:"Lower body: squats and lunges",dur:"30 min",desc:"3 sets of goblet squats. 3 sets of walking lunges each leg. 2 sets of calf raises."},
     {t:"Single-leg balance work",dur:"10 min",desc:"Single-leg Romanian deadlifts, 3 sets each side. Builds stability and identifies imbalances."},
     {t:"Core circuit",dur:"10 min",desc:"Dead bugs, bird dogs, and side planks. 2 rounds of 30 seconds each."},
     {t:"Rest day: walk and stretch",dur:"20 min",desc:"Active recovery. Walk for 15 minutes and stretch for 5. Movement aids muscle repair."}],
    [{t:"Full-body circuit",dur:"30 min",desc:"Squat to press, bent-over row, push-up, lunge. 3 rounds of 10 reps each. Rest 90 seconds between rounds."},
     {t:"Push workout progression",dur:"30 min",desc:"Increase weight or reps from week 2. Add 1 rep per set or go up 2-5 lbs."},
     {t:"Pull workout progression",dur:"30 min",desc:"Same principle: beat last week's numbers by at least 1 rep or small weight increase."},
     {t:"Meal planning for recovery",dur:"10 min",desc:"Plan meals with 0.7-1g protein per pound of body weight. Focus on post-workout nutrition."}],
    [{t:"Progressive overload check",dur:"10 min",desc:"Review your log. Are weights going up week over week? If not, adjust sets or reps."},
     {t:"Upper body focus",dur:"30 min",desc:"4 sets of push-ups, 4 sets of rows, 3 sets of lateral raises. Push for 1-2 more reps than last time."},
     {t:"Lower body focus",dur:"30 min",desc:"4 sets of squats, 3 sets of lunges, 3 sets of hip thrusts. Increase weight if form is solid."},
     {t:"Flexibility session",dur:"15 min",desc:"Full-body stretching routine. Target areas that feel tight from increased training volume."}],
    [{t:"Volume training: upper",dur:"30 min",desc:"Increase total sets by 20%. 5 sets of push-ups, 5 sets of rows. Focus on controlled tempo."},
     {t:"Volume training: lower",dur:"30 min",desc:"5 sets of squats, 4 sets of lunges, 3 sets of deadlifts. Controlled eccentric on every rep."},
     {t:"Track body measurements",dur:"5 min",desc:"Measure arms, chest, waist, and legs. Progress photos tell more than the scale."},
     {t:"Nutrition check-in",dur:"10 min",desc:"Are you eating enough to support growth? Adjust calories up if recovery feels slow."}],
    [{t:"Deload: reduce weight 40%",dur:"30 min",desc:"Use 60% of your normal weights. Same exercises, same form, less intensity. Recovery week."},
     {t:"Mobility deep dive",dur:"20 min",desc:"Extended stretching and foam rolling session. Hit every muscle group for 2 minutes each."},
     {t:"Review training log",dur:"15 min",desc:"Compare week 1 to week 6 numbers. Calculate total strength gains."},
     {t:"Plan next training block",dur:"10 min",desc:"Decide: continue building or shift focus. Set goals for the next 8 weeks."}],
    [{t:"New program design",dur:"20 min",desc:"Using everything you have learned, design your own 4-day split. Push/pull/legs/full body."},
     {t:"Test new maxes",dur:"30 min",desc:"Find your new working weight for squat, push-up, and row. Compare to week 1 assessment."},
     {t:"Set long-term goals",dur:"10 min",desc:"Where do you want to be in 6 months? Write specific strength targets."},
     {t:"Commit to consistency",dur:"5 min",desc:"Block your training schedule for the next month. Consistency is the only secret."}],
  ],
  "nutrition": [
    [{t:"Photograph every meal",dur:"All day",desc:"Take a photo of everything you eat and drink for 3 days. No changes yet, just awareness."},
     {t:"Identify your top 3 patterns",dur:"10 min",desc:"Review your photos. What shows up most? Late-night snacking? Skipping meals? Fast food?"},
     {t:"Check your hydration",dur:"All day",desc:"Drink at least 8 glasses of water today. Track each one with a simple tally."},
     {t:"Rate your energy after meals",dur:"2 min",desc:"After each meal, note if you feel energized, sluggish, or no change. 1-5 scale."}],
    [{t:"Calculate your protein needs",dur:"10 min",desc:"Multiply body weight (lbs) by 0.7. That is your daily protein target in grams."},
     {t:"Add protein to breakfast",dur:"5 min",desc:"Eggs, Greek yogurt, or a protein shake. Aim for 25-30g of protein in your first meal."},
     {t:"Learn to read labels",dur:"5 min",desc:"Pick 3 items from your kitchen. Find calories, protein, fiber, and added sugar on each label."},
     {t:"Swap one processed snack",dur:"2 min",desc:"Replace one packaged snack with fruit, nuts, or vegetables. Small swaps compound."}],
    [{t:"Batch cook one protein",dur:"30 min",desc:"Cook 4-5 servings of chicken, ground turkey, or beans. Store for the week. Prep reduces decisions."},
     {t:"Prep vegetables for the week",dur:"15 min",desc:"Wash and chop enough vegetables for 4 days. Store in containers. Remove friction from healthy eating."},
     {t:"Plan 3 dinners",dur:"10 min",desc:"Write out 3 dinner recipes for the next 3 days. Make a grocery list. Shop once."},
     {t:"Pack tomorrow's lunch",dur:"10 min",desc:"Prepare lunch the night before. You make better choices when not hungry and rushed."}],
    [{t:"Practice the 80/20 meal",dur:"All day",desc:"Eat at a social event or restaurant. Make 80% of your plate nutritious, enjoy 20% freely."},
     {t:"Navigate a restaurant menu",dur:"5 min",desc:"Before going out, look at the menu. Choose a protein-forward option with vegetables."},
     {t:"No-guilt flexibility practice",dur:"5 min",desc:"Eat something indulgent with zero guilt. Write how it felt. Restriction causes rebounds."},
     {t:"Reflect on social pressure",dur:"5 min",desc:"Journal about times you eat to fit in or avoid awkwardness. Awareness is the first step."}],
    [{t:"Identify emotional eating triggers",dur:"10 min",desc:"Write down 3 times you ate when not hungry this week. What emotion preceded it?"},
     {t:"Create a non-food coping list",dur:"10 min",desc:"List 5 things you can do instead of eating when stressed: walk, call a friend, stretch, journal, breathe."},
     {t:"Practice hunger vs craving check",dur:"2 min",desc:"Before eating, ask: am I hungry or just wanting? Wait 10 minutes. If still hungry, eat."},
     {t:"Journal: your relationship with food",dur:"10 min",desc:"Write honestly about how you feel about food. No judgment. Understanding drives lasting change."}],
    [{t:"Design your sustainable plate",dur:"10 min",desc:"Create your template: half plate vegetables, quarter protein, quarter carbs. This is your default."},
     {t:"Audit your environment",dur:"10 min",desc:"Remove trigger foods from visible spots. Put healthy options at eye level. Environment beats willpower."},
     {t:"Plan meals for a full week",dur:"15 min",desc:"Write out all 7 dinners. Create one consolidated grocery list. Batch shop on one day."},
     {t:"Celebrate your changes",dur:"5 min",desc:"List 5 nutrition improvements since week 1. You are building a sustainable system, not a diet."}],
  ],
  "running": [
    [{t:"Walk/run intervals: 20 min",dur:"20 min",desc:"Walk 3 minutes, jog 1 minute. Repeat 5 times. Focus on breathing and posture, not speed."},
     {t:"Post-run stretching",dur:"5 min",desc:"Stretch calves, quads, hamstrings, and hip flexors. Hold each 20-30 seconds."},
     {t:"Choose your running shoes",dur:"10 min",desc:"Wear shoes with good cushioning. If over a year old, consider replacing them."},
     {t:"Plan 3 run days this week",dur:"5 min",desc:"Block Mon/Wed/Fri or similar. Alternate days let muscles recover between runs."}],
    [{t:"Walk 2 min, run 3 min intervals",dur:"25 min",desc:"Walk 2 minutes, run 3 minutes. Repeat 5 times. You are building aerobic base."},
     {t:"Easy pace check",dur:"5 min",desc:"Can you hold a conversation while running? If not, slow down. Easy runs build endurance faster."},
     {t:"Core work for runners",dur:"10 min",desc:"Planks, dead bugs, and glute bridges. Strong core prevents injuries and improves form."},
     {t:"Hydration before running",dur:"5 min",desc:"Drink 16oz water 2 hours before your run. Proper hydration prevents cramps and fatigue."}],
    [{t:"Run 3 days this week",dur:"25 min",desc:"Run 2 min, walk 1 min. Increase run intervals gradually. Consistency matters more than distance."},
     {t:"Track your weekly distance",dur:"5 min",desc:"Use your phone or a simple map to estimate. Just knowing your baseline helps."},
     {t:"Recovery day: walk only",dur:"20 min",desc:"Walk at a brisk pace. Active recovery helps your body adapt without adding stress."},
     {t:"Foam roll legs",dur:"10 min",desc:"Roll quads, IT bands, calves, and glutes. Spend extra time on sore spots."}],
    [{t:"Continuous 15-minute run",dur:"15 min",desc:"Try running without walk breaks. If you need to walk, that is fine. Push a little further each time."},
     {t:"Add 5 minutes to one run",dur:"20 min",desc:"Pick one session this week and extend it by 5 minutes. Gradual increase prevents injury."},
     {t:"Hill walking or stair climbing",dur:"15 min",desc:"Find a hill or staircase. Walk up with purpose, walk down easy. Builds leg strength for running."},
     {t:"Set a distance goal",dur:"5 min",desc:"Choose a target: a local 5K, a distance, or a streak. Having a goal keeps you motivated."}],
    [{t:"Focus on running form",dur:"20 min",desc:"Run with short strides, landing under your hips. Keep shoulders relaxed, arms at 90 degrees."},
     {t:"Cadence check",dur:"5 min",desc:"Count your steps for 30 seconds, multiply by 2. Aim for 160-180 steps per minute."},
     {t:"Single-leg exercises",dur:"15 min",desc:"Single-leg squats, lunges, and calf raises. Running is single-leg movement, so train that way."},
     {t:"Breathing practice",dur:"5 min",desc:"Practice 3:2 or 2:1 breathing rhythm (steps per inhale:exhale). Find what feels natural."}],
    [{t:"Speed play run",dur:"25 min",desc:"During your run, add 3 bursts of faster running for 30 seconds each. Recover with easy jogging."},
     {t:"Tempo run: comfortably hard",dur:"20 min",desc:"Run at a pace where you can say short sentences but not chat. Hold for 10-15 minutes."},
     {t:"Dynamic warm-up",dur:"5 min",desc:"Before running: leg swings, high knees, butt kicks, side shuffles. Warm muscles perform better."},
     {t:"Track your improvement",dur:"5 min",desc:"Run the same route from week 1. Compare your time and how you feel. Progress is real."}],
    [{t:"30-minute continuous run",dur:"30 min",desc:"Run for 30 minutes without stopping. Any pace is fine. This is a milestone."},
     {t:"Recovery run: easy pace",dur:"20 min",desc:"Run very slowly the day after your long run. Active recovery flushes metabolic waste."},
     {t:"Strength circuit for runners",dur:"15 min",desc:"Squats, lunges, calf raises, planks. 3 rounds. Strength prevents injury for longer runs."},
     {t:"Celebrate 30 minutes",dur:"5 min",desc:"You can now run continuously for 30 minutes. Write down how that feels compared to week 1."}],
    [{t:"Plan a race or event",dur:"10 min",desc:"Find a local 5K or fun run. Register. Having a date creates accountability."},
     {t:"Practice race pace",dur:"25 min",desc:"Run at your target race pace for 15 minutes. Get comfortable with the effort level."},
     {t:"Pre-run nutrition plan",dur:"5 min",desc:"Eat a light carb-rich snack 60-90 minutes before your run. Test what works for your stomach."},
     {t:"Write your running identity",dur:"5 min",desc:"You are a runner now. Write a one-sentence identity statement for your fridge or mirror."}],
  ],
  "deepwork": [
    [{t:"Distraction audit",dur:"15 min",desc:"Track every interruption for one work session. Tally phone checks, notifications, tab switches, people."},
     {t:"Install a website blocker",dur:"5 min",desc:"Block social media, news, and time-wasting sites during work hours. Remove the option."},
     {t:"Disable non-essential notifications",dur:"10 min",desc:"Turn off all notifications except calls and direct messages. Batch everything else."},
     {t:"Identify your peak focus time",dur:"5 min",desc:"When in the day do you think best? Morning? Afternoon? That becomes your deep work window."}],
    [{t:"Schedule your first deep work block",dur:"90 min",desc:"Block 90 minutes in your calendar for focused work. No email, no chat, no meetings."},
     {t:"Set a single task for the block",dur:"5 min",desc:"Choose one important task before starting. Write it on paper. One task per block."},
     {t:"Create a start ritual",dur:"5 min",desc:"Design a 2-minute start routine: close all tabs, put on headphones, open only your task."},
     {t:"Review the block",dur:"5 min",desc:"After your deep work block: what did you accomplish? Where did focus break? What will you adjust?"}],
    [{t:"Deep work block: 90 minutes",dur:"90 min",desc:"Execute your block with the start ritual. Single task, no context switching."},
     {t:"Email batching: 2x per day",dur:"10 min",desc:"Check email only at 11am and 4pm. Batch responses. Most emails can wait hours."},
     {t:"Practice saying no to interruptions",dur:"All day",desc:"When interrupted, say 'I am in a focus block, can I get back to you at [time]?'"},
     {t:"Track deep work hours",dur:"5 min",desc:"Log how many total minutes of deep work you completed today. Aim to increase weekly."}],
    [{t:"Two deep work blocks today",dur:"3 hrs",desc:"Schedule a morning and afternoon deep work block. 90 minutes each with a break between."},
     {t:"Create a shutdown ritual",dur:"10 min",desc:"At end of workday: review tomorrow's tasks, close all loops, say 'shutdown complete.' Be done."},
     {t:"Design your ideal workspace",dur:"15 min",desc:"Minimize visual clutter, set up proper lighting, and make your deep work spot feel intentional."},
     {t:"Weekly deep work review",dur:"10 min",desc:"Total your deep work hours this week. Set a target for next week that is 10% higher."}],
  ],
  "leadership": [
    [{t:"Take a leadership style quiz",dur:"15 min",desc:"Identify your natural style: directive, coaching, supportive, or delegative. Know your default."},
     {t:"Journal: your leadership gaps",dur:"10 min",desc:"Write 3 situations where you felt uncomfortable leading. What skill was missing?"},
     {t:"Observe a leader you admire",dur:"10 min",desc:"Watch how they communicate, decide, and handle conflict. Note one thing to emulate."},
     {t:"Ask for honest feedback",dur:"5 min",desc:"Ask one colleague: 'What is one thing I could do better as a leader?' Listen without defending."}],
    [{t:"Practice active listening",dur:"All day",desc:"In every conversation today, listen fully before responding. No interrupting, no planning your reply."},
     {t:"Summarize before responding",dur:"All day",desc:"Before giving your opinion, summarize what the other person said. 'So what I hear is...'"},
     {t:"Ask open-ended questions",dur:"All day",desc:"Replace yes/no questions with 'What do you think about...' and 'How would you approach...'"},
     {t:"Journal: listening wins",dur:"5 min",desc:"Write about a moment today when listening changed the outcome of a conversation."}],
    [{t:"Delegate one task today",dur:"15 min",desc:"Choose something you normally do yourself. Brief someone clearly with the outcome, deadline, and context."},
     {t:"Define clear outcomes",dur:"10 min",desc:"For every task you assign this week, write the specific result you expect. Share it in writing."},
     {t:"Check in without micromanaging",dur:"5 min",desc:"Ask 'How is it going? Do you need anything?' Not 'Show me what you have done.'"},
     {t:"Reflect on control",dur:"5 min",desc:"Journal about what was hard about letting go. What is the cost of not delegating?"}],
    [{t:"Prepare for a hard conversation",dur:"15 min",desc:"Identify one difficult conversation you are avoiding. Write what you need to say and the outcome you want."},
     {t:"Use the SBI framework",dur:"10 min",desc:"Situation, Behavior, Impact. 'In [situation], when you [behavior], it caused [impact].' Practice this."},
     {t:"Give positive feedback today",dur:"5 min",desc:"Catch someone doing something well. Be specific: 'The way you handled X was effective because Y.'"},
     {t:"Debrief the conversation",dur:"10 min",desc:"After the hard conversation, journal: what went well, what was uncomfortable, what would you change?"}],
    [{t:"Define your team values",dur:"15 min",desc:"Write 3 values you want your team to embody. How will you model each one yourself?"},
     {t:"Run a team check-in",dur:"15 min",desc:"Ask each person: what is working, what is not, what do you need from me? Listen and take notes."},
     {t:"Recognize someone publicly",dur:"5 min",desc:"In a meeting or group chat, acknowledge a team member's contribution. Be specific about what they did."},
     {t:"Create psychological safety",dur:"10 min",desc:"Share a recent mistake you made and what you learned. Vulnerability from leaders builds trust."}],
    [{t:"Write your leadership vision",dur:"15 min",desc:"In 3 sentences: what kind of leader do you want to be? What impact do you want to have?"},
     {t:"Set a 90-day leadership goal",dur:"10 min",desc:"Choose one leadership skill to develop over the next 3 months. Define what success looks like."},
     {t:"Find an accountability partner",dur:"5 min",desc:"Ask a peer or mentor to check in monthly on your leadership development."},
     {t:"Journal: how far you have come",dur:"10 min",desc:"Compare your week 1 self-assessment to now. What has shifted in how you lead?"}],
  ],
  "negotiate": [
    [{t:"Practice tactical empathy",dur:"15 min",desc:"In one conversation today, label the other person's emotion: 'It sounds like you are frustrated by...'."},
     {t:"Study your negotiation history",dur:"10 min",desc:"Write about a past negotiation. What worked? Where did you give in too easily?"},
     {t:"The accusation audit",dur:"10 min",desc:"Before a tough conversation, list every negative thing they might think about you. Address each one upfront."},
     {t:"Practice calibrated questions",dur:"5 min",desc:"Prepare 3 'how' and 'what' questions for your next negotiation. Never ask 'why.' It sounds accusatory."}],
    [{t:"Mirror exercise",dur:"All day",desc:"In conversations, repeat the last 1-3 words someone says. It encourages them to elaborate without you asking."},
     {t:"Practice the late-night FM DJ voice",dur:"10 min",desc:"Lower your voice, speak slowly, with a slight downward inflection. It creates calm and authority."},
     {t:"Active listening practice",dur:"All day",desc:"Aim for the other person to talk 70% of the time. Your power comes from understanding, not talking."},
     {t:"Journal: what you learned by listening",dur:"5 min",desc:"Write one insight you gained today because you listened longer than usual."}],
    [{t:"Prepare calibrated questions",dur:"15 min",desc:"For your next negotiation, write 5 'how' questions: 'How am I supposed to do that?' 'How does this work?'"},
     {t:"Practice saying no without saying no",dur:"10 min",desc:"Use 'How am I supposed to do that?' instead of 'No.' It makes them solve your problem."},
     {t:"Identify their 'black swan'",dur:"10 min",desc:"What do they want that they are not saying? What hidden motivation drives their position?"},
     {t:"Role-play a scenario",dur:"15 min",desc:"Practice a negotiation with a friend. Have them play hard. Use mirroring and calibrated questions."}],
    [{t:"Set your walkaway point",dur:"10 min",desc:"Before any negotiation, know your limit. Write it down. Knowing when to walk away is your greatest power."},
     {t:"Practice the Ackerman model",dur:"15 min",desc:"Set target price, then offer 65%, 85%, 95%, 100% in sequence. Include non-monetary items in final offer."},
     {t:"Get to 'that is right'",dur:"All day",desc:"In one conversation, keep summarizing until they say 'That is right.' It means they feel heard."},
     {t:"Debrief your negotiation",dur:"10 min",desc:"After any negotiation this week: what tactics worked? Where did emotion override strategy?"}],
  ],
  "career-pivot": [
    [{t:"Values inventory",dur:"20 min",desc:"List your top 10 work values: autonomy, impact, creativity, money, flexibility. Rank them honestly."},
     {t:"Energy audit",dur:"10 min",desc:"List tasks that energize you vs drain you in your current role. This reveals your natural strengths."},
     {t:"Write your ideal Tuesday",dur:"10 min",desc:"Describe a perfect work day 2 years from now. Where are you? What are you doing? Who is around?"},
     {t:"Define your non-negotiables",dur:"10 min",desc:"List 3 things your next role must have and 3 things it must not have."}],
    [{t:"Research 3 target roles",dur:"20 min",desc:"Find 3 job titles that match your values. Read 5 job descriptions for each. Note common requirements."},
     {t:"Informational interview prep",dur:"15 min",desc:"Identify 3 people in your target field. Draft a short message requesting a 20-minute conversation."},
     {t:"Explore adjacent industries",dur:"15 min",desc:"Your skills transfer more than you think. List 3 industries where your experience would be valued."},
     {t:"Shadow or volunteer",dur:"10 min",desc:"Find one way to experience your target role without committing: volunteering, freelancing, or a side project."}],
    [{t:"Conduct an informational interview",dur:"30 min",desc:"Talk to someone in your target role. Ask: what do you actually do daily? What surprised you about this job?"},
     {t:"Compare expectations vs reality",dur:"10 min",desc:"Based on your interview, how does the real role match your ideal Tuesday? Adjust if needed."},
     {t:"Research salary ranges",dur:"10 min",desc:"Look up compensation for your target roles on 2-3 salary sites. Know your market value before applying."},
     {t:"Journal: fears and excitement",dur:"10 min",desc:"Write about what scares you and excites you about this change. Both are useful data."}],
    [{t:"Identify your skill gaps",dur:"15 min",desc:"Compare your current skills to job requirements. List gaps. Which can you learn quickly? Which need formal training?"},
     {t:"Start one skill-building activity",dur:"20 min",desc:"Take the first lesson of an online course, read a chapter, or do a practice project in your gap area."},
     {t:"Update your resume",dur:"20 min",desc:"Rewrite your resume targeting your new direction. Lead with transferable skills and relevant accomplishments."},
     {t:"Build your transition narrative",dur:"10 min",desc:"Write a 30-second story explaining your pivot. Why this change? Why now? Why you?"}],
    [{t:"Draft a transition timeline",dur:"15 min",desc:"Set milestones: when to start applying, target start date, financial runway needed. Be realistic."},
     {t:"Financial bridge plan",dur:"15 min",desc:"Calculate savings needed if there is a gap. Can you freelance during transition? Reduce expenses?"},
     {t:"Tell one trusted person",dur:"10 min",desc:"Share your plan with someone supportive. Saying it out loud makes it real and creates accountability."},
     {t:"Apply to one role",dur:"20 min",desc:"Submit one application this week. Imperfect action beats perfect planning."}],
    [{t:"Set up weekly applications",dur:"15 min",desc:"Commit to applying to 3 roles per week. Block time in your calendar. Treat job searching as a job."},
     {t:"Practice your interview story",dur:"15 min",desc:"Rehearse your transition narrative out loud. Time it. Refine until it feels natural and confident."},
     {t:"Build one new connection",dur:"10 min",desc:"Connect with someone in your target field on LinkedIn. Send a personalized note referencing their work."},
     {t:"Celebrate taking action",dur:"5 min",desc:"You are doing the hardest part: starting. Write what you are proud of since week 1."}],
  ],
  "financial": [
    [{t:"Set up automatic savings",dur:"15 min",desc:"Create an automatic transfer from checking to savings on payday. Even $25 per paycheck builds the habit."},
     {t:"Link all accounts",dur:"10 min",desc:"List every bank account, credit card, and loan. Know your complete financial picture."},
     {t:"Calculate your net worth",dur:"10 min",desc:"Assets minus debts equals net worth. Write this number down. This is your starting point."},
     {t:"Automate one bill",dur:"5 min",desc:"Set up autopay for your most consistent bill. Automation removes decision fatigue and late fees."}],
    [{t:"Track spending for 3 days",dur:"5 min",desc:"Write down every purchase for 3 days. Include small items. Awareness changes behavior."},
     {t:"Categorize last month's spending",dur:"15 min",desc:"Group expenses: housing, food, transport, entertainment, subscriptions. Where does the money actually go?"},
     {t:"Identify your top money leak",dur:"5 min",desc:"Find the one category where you spend more than you thought. Subscriptions and eating out are common culprits."},
     {t:"Create a spending plan",dur:"15 min",desc:"Allocate percentages: 50% needs, 30% wants, 20% savings/debt. Adjust based on your actual situation."}],
    [{t:"List all debts with interest rates",dur:"10 min",desc:"Write each debt, balance, minimum payment, and interest rate. Order from highest to lowest interest."},
     {t:"Choose avalanche or snowball",dur:"10 min",desc:"Avalanche: pay highest interest first (saves money). Snowball: pay smallest balance first (builds momentum)."},
     {t:"Find $50 to redirect to debt",dur:"10 min",desc:"Cancel one subscription, pack lunch twice, skip one purchase. Redirect that money to your highest priority debt."},
     {t:"Set a debt-free target date",dur:"5 min",desc:"Calculate when you will be debt-free at current payments. Then calculate with extra payments. See the difference."}],
    [{t:"Open an investment account",dur:"15 min",desc:"If you do not have one, open a brokerage or IRA account. You do not need to fund it yet, just open it."},
     {t:"Set up automatic investing",dur:"10 min",desc:"Automate a monthly transfer to your investment account. Start with whatever you can afford."},
     {t:"Learn the 3-fund portfolio",dur:"10 min",desc:"Total US stock index, international stock index, and bond index. Simple, diversified, low-cost."},
     {t:"Review and celebrate",dur:"10 min",desc:"List every financial system you automated this month. You built infrastructure that works while you sleep."}],
  ],
  "investing": [
    [{t:"Read about loss aversion",dur:"15 min",desc:"Losses feel twice as painful as gains feel good. Understanding this bias prevents panic selling."},
     {t:"Write your investing statement",dur:"10 min",desc:"In one sentence: why are you investing? What is this money for? When do you need it?"},
     {t:"Calculate your risk tolerance",dur:"10 min",desc:"If your portfolio dropped 30%, would you sell, hold, or buy more? Your honest answer sets your allocation."},
     {t:"Journal: money beliefs",dur:"10 min",desc:"What did you learn about money growing up? These beliefs drive your investment behavior."}],
    [{t:"Learn asset allocation basics",dur:"15 min",desc:"Stocks for growth, bonds for stability. Your age and timeline determine the mix."},
     {t:"Research index funds",dur:"15 min",desc:"Compare the returns of actively managed funds vs index funds over 20 years. The data is clear."},
     {t:"Understand compound interest",dur:"10 min",desc:"$200/month at 8% becomes $590K in 30 years. Run the numbers for your situation. Time is the asset."},
     {t:"Learn what fees cost you",dur:"10 min",desc:"A 1% fee vs 0.03% on $100K over 30 years costs you over $100K. Always check expense ratios."}],
    [{t:"Set up your accounts",dur:"15 min",desc:"Open or review your IRA and 401k. Are you getting the full employer match? That is free money."},
     {t:"Automate monthly contributions",dur:"10 min",desc:"Set up automatic investment on the 1st of each month. Remove the decision to invest."},
     {t:"Choose your funds",dur:"15 min",desc:"Select 2-3 low-cost index funds. Total market, international, and bonds if desired. Keep it simple."},
     {t:"Set calendar reminders",dur:"5 min",desc:"Quarterly rebalancing reminder and annual contribution increase. Automate your investment management."}],
    [{t:"Write your investment policy",dur:"15 min",desc:"Document: what you invest in, how much monthly, when you rebalance, when you sell (never in panic)."},
     {t:"Stress test your plan",dur:"10 min",desc:"Imagine a 40% market drop. Read your policy statement. Would you follow it? If not, adjust your allocation."},
     {t:"Plan contribution increases",dur:"10 min",desc:"Every time you get a raise, increase investment by half the raise amount. Lifestyle inflation is the enemy."},
     {t:"Celebrate starting",dur:"5 min",desc:"Most people never start investing. You have a plan, automated contributions, and a written policy. That is rare."}],
  ],
  "side-income": [
    [{t:"Skills inventory",dur:"15 min",desc:"List every skill you have: professional, hobby, and life skills. What would someone pay you for?"},
     {t:"Research demand",dur:"15 min",desc:"Search freelance platforms for your skills. What are people paying? What problems do they need solved?"},
     {t:"Talk to 3 potential customers",dur:"20 min",desc:"Describe your idea to 3 people. Ask: would you pay for this? How much? What would make it better?"},
     {t:"Define your minimum viable offer",dur:"10 min",desc:"What is the simplest version of your service you could deliver this week? Start there."}],
    [{t:"Validate with a test sale",dur:"20 min",desc:"Offer your service at a discount to one person. Getting paid validates demand better than any survey."},
     {t:"Set up a simple landing page",dur:"20 min",desc:"Create a one-page description of what you offer: problem you solve, how it works, price, how to buy."},
     {t:"Collect a testimonial",dur:"5 min",desc:"Ask your first customer for a brief testimonial. Social proof makes future sales easier."},
     {t:"Set income targets",dur:"10 min",desc:"Month 1: first dollar. Month 3: $500/month. Month 6: $1000/month. Write your targets."}],
    [{t:"Build your minimum viable product",dur:"30 min",desc:"Create the simplest version of your offering. A template, a guide, a service package. Ship imperfect."},
     {t:"Price with confidence",dur:"10 min",desc:"Research competitor pricing. Price 10% below market to start. Raise as you get testimonials."},
     {t:"Create a delivery workflow",dur:"15 min",desc:"Map the steps from customer purchase to delivery. Where can you automate or template?"},
     {t:"Serve your first paid customer",dur:"Varies",desc:"Deliver excellent work to your first customer. Over-deliver. Referrals come from exceeding expectations."}],
    [{t:"Ask for 2 referrals",dur:"10 min",desc:"Contact past customers and ask: do you know anyone who needs this? Referrals convert at 3-5x cold outreach."},
     {t:"Post about your offering",dur:"10 min",desc:"Share what you do on one social platform. Describe the problem you solve, not just your service."},
     {t:"Respond to all inquiries within 2 hours",dur:"All day",desc:"Speed wins customers. Fast response signals professionalism and reliability."},
     {t:"Track revenue and time",dur:"10 min",desc:"Calculate your effective hourly rate. If too low, raise prices or find ways to deliver faster."}],
    [{t:"Time audit: where do the hours go?",dur:"10 min",desc:"Track time spent on your side project for 3 days. Separate production work from admin and marketing."},
     {t:"Set work boundaries",dur:"10 min",desc:"Block specific hours for side income work. Protect evenings or mornings. Burnout kills side projects."},
     {t:"Create a template or system",dur:"20 min",desc:"Templatize your most repeated task. Every template saves future time and increases consistency."},
     {t:"Review: is this sustainable?",dur:"10 min",desc:"Honestly assess: can you maintain this pace? Adjust scope, pricing, or hours if needed."}],
    [{t:"Raise your prices 15%",dur:"10 min",desc:"You now have testimonials and experience. Raise prices for new customers. Grandfather existing ones if you want."},
     {t:"Explore passive income angles",dur:"15 min",desc:"Can you turn your service into a digital product, course, or template? Create once, sell repeatedly."},
     {t:"Set a 6-month revenue goal",dur:"10 min",desc:"Based on current trajectory, what is realistic? What would need to change to double it?"},
     {t:"Celebrate your side income",dur:"5 min",desc:"You built something from nothing. Write down your total revenue and what it means to you."}],
  ],
  "communication": [
    [{t:"Identify your communication patterns",dur:"15 min",desc:"Do you criticize, get defensive, stonewall, or show contempt? These four predict relationship failure."},
     {t:"Notice your first reaction",dur:"All day",desc:"When your partner says something that bothers you, pause. Notice your body reaction before responding."},
     {t:"Practice 'I' statements",dur:"All day",desc:"Replace 'You always...' with 'I feel... when... because...' Own your experience."},
     {t:"Journal: your triggers",dur:"10 min",desc:"Write 3 things your partner does that trigger you. For each, write the deeper feeling underneath."}],
    [{t:"Listen without solving",dur:"All day",desc:"When your partner shares a problem, ask 'Do you want advice or just someone to listen?' Then do that."},
     {t:"Reflect back emotions",dur:"All day",desc:"After they speak, say 'It sounds like you feel [emotion] about [topic].' Validation before solution."},
     {t:"Put away your phone during conversations",dur:"All day",desc:"Full attention. No glancing at screens. Eye contact shows you are present."},
     {t:"Ask one meaningful question",dur:"5 min",desc:"Ask your partner something deeper than logistics: 'What was the best part of your day? What stressed you?'"}],
    [{t:"Learn the repair attempt",dur:"10 min",desc:"When conflict escalates, try a repair: humor, a touch, 'Can we start over?' 'I am sorry, that came out wrong.'"},
     {t:"Practice accepting repair attempts",dur:"All day",desc:"When your partner tries to de-escalate, let them. Accepting repair matters more than who was right."},
     {t:"Cool-down protocol",dur:"5 min",desc:"If you feel flooded with emotion, say 'I need 20 minutes to calm down, then let us talk.' Return to it."},
     {t:"Apologize for one thing",dur:"5 min",desc:"Think of something recent you handled poorly. Apologize specifically. No 'but' or justification."}],
    [{t:"5:1 positivity practice",dur:"All day",desc:"For every negative interaction, aim for 5 positive ones. Compliments, appreciation, affection, humor, interest."},
     {t:"Express appreciation",dur:"5 min",desc:"Tell your partner one specific thing you appreciate about them. Not generic, but something concrete from today."},
     {t:"Create a daily connection ritual",dur:"15 min",desc:"A 6-second kiss, a 10-minute coffee together, or a walk. Small rituals maintain connection."},
     {t:"Weekly state of the union",dur:"20 min",desc:"Set a weekly 20-minute check-in: what went well, what needs attention, what do you need from each other?"}],
  ],
  "boundaries": [
    [{t:"Identify your boundary patterns",dur:"15 min",desc:"Where do you say yes when you mean no? List 3 situations where you feel resentful or overextended."},
     {t:"Recognize the cost of no boundaries",dur:"10 min",desc:"For each pattern, write the cost: exhaustion, resentment, lost time, strained relationships."},
     {t:"Define your non-negotiable needs",dur:"10 min",desc:"List 5 things you need to function well: sleep, alone time, exercise, creative time. These are non-negotiable."},
     {t:"Practice saying no in low-stakes situations",dur:"All day",desc:"Decline one small request today. 'I can not make that work.' No explanation needed."}],
    [{t:"Set one boundary this week",dur:"10 min",desc:"Choose a specific boundary to set. Write the exact words you will use. Practice saying them out loud."},
     {t:"Use the boundary formula",dur:"All day",desc:"'I need [boundary] because [reason]. I would love to [alternative].' Be clear, kind, and firm."},
     {t:"Handle the guilt",dur:"10 min",desc:"Journal about guilt after setting a boundary. Guilt means you are growing, not that you were wrong."},
     {t:"Notice when boundaries are respected",dur:"5 min",desc:"Write about a time someone respected your boundary today. How did it feel? This reinforces the behavior."}],
    [{t:"Identify your difficult person",dur:"10 min",desc:"Who regularly crosses your boundaries? What pattern do they use: guilt, anger, withdrawal, charm?"},
     {t:"Prepare for pushback",dur:"10 min",desc:"Write scripts for when they push back: 'I understand you are upset, and this is what I need.'"},
     {t:"Practice broken record technique",dur:"10 min",desc:"Repeat your boundary calmly without engaging in arguments. Same words, calm tone, every time."},
     {t:"Celebrate a boundary win",dur:"5 min",desc:"Write about a boundary you held this week. What changed because of it? How do you feel?"}],
  ],
  "habits": [
    [{t:"Habit audit",dur:"15 min",desc:"List your daily habits: morning to night. Mark each as serving you (+), neutral (=), or harmful (-). No judgment."},
     {t:"Choose one habit to build",dur:"5 min",desc:"Pick one small positive habit. Make it absurdly easy: 1 push-up, open one book, put on running shoes."},
     {t:"Identify the cue",dur:"10 min",desc:"When and where will this habit happen? After what existing habit? Stack it: 'After I pour my coffee, I will...'."},
     {t:"Track day 1",dur:"2 min",desc:"Did you do it? Check the box. Streaks create momentum. The goal is not to break the chain."}],
    [{t:"Make the cue obvious",dur:"10 min",desc:"Put visual triggers in your environment. Running shoes by the door. Book on the pillow. Water bottle on desk."},
     {t:"Design your environment",dur:"15 min",desc:"Remove cues for bad habits, add cues for good ones. Make good choices the default, not the exception."},
     {t:"Implementation intention",dur:"5 min",desc:"Write: 'I will [habit] at [time] in [location].' Specific plans are 2-3x more likely to succeed."},
     {t:"Track your streak",dur:"2 min",desc:"Mark today on your tracker. How many days in a row? Protect the streak."}],
    [{t:"Make the habit attractive",dur:"10 min",desc:"Pair your habit with something you enjoy. Listen to a favorite podcast only while exercising."},
     {t:"Temptation bundling",dur:"5 min",desc:"'I will only [thing I want] while doing [thing I need].' Link pleasure to productive behavior."},
     {t:"Join a group",dur:"10 min",desc:"Find people who share your desired habit. We adopt the behaviors of those around us."},
     {t:"Track and review",dur:"5 min",desc:"Review your habit tracker. Are you consistent? If you missed, what happened? Adjust the system, not the goal."}],
    [{t:"Reduce friction",dur:"10 min",desc:"How can you make the habit take less effort? Prepare the night before. Simplify the steps."},
     {t:"Two-minute rule",dur:"All day",desc:"When starting your habit, commit to only 2 minutes. Anyone can do 2 minutes. Momentum does the rest."},
     {t:"Automate what you can",dur:"10 min",desc:"Set up automatic triggers: app reminders, alarm clocks, pre-scheduled calendar blocks."},
     {t:"Practice on hard days",dur:"5 min",desc:"Today, do the minimum version of your habit even if you do not feel like it. Showing up matters most."}],
    [{t:"Stack a second habit",dur:"10 min",desc:"Your first habit is becoming automatic. Add a second one linked to it. Chain them together."},
     {t:"Create a reward",dur:"5 min",desc:"After completing your habit chain, give yourself an immediate reward. Satisfaction reinforces repetition."},
     {t:"Habit contract",dur:"10 min",desc:"Write a commitment: 'I will do [habit] for [timeframe]. If I miss, [consequence]. Signed: me.'"},
     {t:"Teach someone else",dur:"10 min",desc:"Explain your habit system to someone. Teaching deepens understanding and creates accountability."}],
    [{t:"Build your identity",dur:"10 min",desc:"Shift from 'I want to run' to 'I am a runner.' Every habit is a vote for the person you want to become."},
     {t:"Review your system",dur:"15 min",desc:"What is working? What is not? Adjust cues, rewards, and environment. Systems beat goals."},
     {t:"Plan for disruptions",dur:"10 min",desc:"Travel, illness, holidays. Write your plan for maintaining habits when life disrupts your routine."},
     {t:"Celebrate your identity shift",dur:"5 min",desc:"List all the habits that are now automatic. You did not just build habits. You changed who you are."}],
  ],
  "mindfulness": [
    [{t:"5-minute breath awareness",dur:"5 min",desc:"Sit comfortably. Focus on your breath. When your mind wanders (it will), gently return to breathing."},
     {t:"Notice 5 things",dur:"5 min",desc:"Right now: name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste."},
     {t:"Set a mindfulness alarm",dur:"2 min",desc:"Set 3 random alarms today. When they ring, take 3 conscious breaths. Practice presence in daily life."},
     {t:"Journal: where is your mind?",dur:"5 min",desc:"Write about where your thoughts went today. Past? Future? Worries? Just observe the pattern."}],
    [{t:"10-minute body scan",dur:"10 min",desc:"Start at your toes, slowly move attention up through your body. Notice sensations without judging them."},
     {t:"Mindful eating: one meal",dur:"15 min",desc:"Eat one meal slowly. Notice flavors, textures, temperature. Put down your fork between bites."},
     {t:"Label your thoughts",dur:"All day",desc:"When a thought arises, label it: 'planning,' 'worrying,' 'remembering.' This creates space between you and your thoughts."},
     {t:"Gratitude moment",dur:"3 min",desc:"Before bed, name 3 specific things from today you are grateful for. Feel each one."}],
    [{t:"Walking meditation: 10 min",dur:"10 min",desc:"Walk slowly, feeling each footstep. Heel, ball, toes. Notice the ground beneath you. No destination."},
     {t:"Mindful transitions",dur:"All day",desc:"Before each new activity, take one breath. Between meetings, before meals, when arriving home. Reset."},
     {t:"Sitting meditation: 10 min",dur:"10 min",desc:"Sit with eyes closed. Follow breath. When distracted, note it, return. No judgment. This is the practice."},
     {t:"Loving-kindness practice",dur:"5 min",desc:"Silently wish well to yourself, someone you love, a neutral person, and someone difficult. 'May you be happy. May you be safe.'"}],
    [{t:"Morning meditation: 10 min",dur:"10 min",desc:"Meditate before checking your phone. This sets the tone for your entire day."},
     {t:"Anchor practice",dur:"All day",desc:"Choose one daily activity as your mindfulness anchor: brushing teeth, walking to car, first sip of coffee. Be fully present."},
     {t:"Accept discomfort",dur:"5 min",desc:"Sit with an uncomfortable emotion for 2 minutes without fixing it. Notice it, breathe with it. It passes."},
     {t:"Week 4 reflection",dur:"10 min",desc:"How has your relationship with your own mind changed? Write about one moment of peace you found this month."}],
  ],
  "gratitude": [
    [{t:"Morning gratitude: 3 specifics",dur:"5 min",desc:"Write 3 things you are grateful for. Be specific: not 'my family' but 'my daughter's laugh at breakfast.'"},
     {t:"Why it matters",dur:"3 min",desc:"For each item, write one sentence about why it matters to you. Depth beats quantity."},
     {t:"Gratitude photo",dur:"2 min",desc:"Take one photo of something you are grateful for today. Build a visual gratitude collection."},
     {t:"Evening review",dur:"3 min",desc:"Before sleep, name the best moment of your day. Relive it. Let the feeling settle in your body."}],
    [{t:"Write a gratitude message",dur:"10 min",desc:"Text, email, or write a note to someone you appreciate. Be specific about their impact on your life."},
     {t:"Express appreciation face-to-face",dur:"5 min",desc:"Tell one person today what you appreciate about them. Watch how it changes the interaction."},
     {t:"Gratitude for ordinary things",dur:"5 min",desc:"Write gratitude for 3 things you usually take for granted: running water, a warm bed, electricity."},
     {t:"Notice generosity around you",dur:"All day",desc:"Pay attention to small acts of kindness today. Someone holding a door, a colleague helping out."}],
    [{t:"Gratitude in difficulty",dur:"10 min",desc:"Think of a recent challenge. Write one thing it taught you or one way it made you stronger."},
     {t:"Reframe a complaint",dur:"5 min",desc:"Take something you complained about this week. Find one positive aspect. Not toxic positivity, genuine reframing."},
     {t:"Gratitude letter",dur:"15 min",desc:"Write a letter to someone who shaped your life. You do not have to send it. The writing is the practice."},
     {t:"Review your gratitude journey",dur:"5 min",desc:"Read through all your gratitude entries. Notice patterns. What consistently brings you joy?"}],
  ],
  "creativity": [
    [{t:"Creative identity statement",dur:"10 min",desc:"Write: 'I am a creative person who...' Fill it in. Creativity is not a talent, it is an identity."},
     {t:"30-minute creative time",dur:"30 min",desc:"Block 30 minutes for creating anything: write, draw, build, cook, photograph. No goals, just play."},
     {t:"Consume something inspiring",dur:"15 min",desc:"Visit a gallery, watch a documentary, read poetry, listen to a new genre. Input fuels output."},
     {t:"Creative journal",dur:"5 min",desc:"Write 3 ideas before bed. They can be terrible. The practice of generating ideas builds the muscle."}],
    [{t:"Micro-creation: 10 minutes",dur:"10 min",desc:"Create something small in 10 minutes. A sketch, a haiku, a melody, a recipe variation. Finished beats perfect."},
     {t:"Copy then remix",dur:"15 min",desc:"Pick something you admire and recreate it, then change 3 things. All creativity builds on what came before."},
     {t:"Share one creation",dur:"5 min",desc:"Show someone something you made. A friend, a family member, social media. Sharing completes the creative act."},
     {t:"Document your process",dur:"5 min",desc:"Take a photo or note about how you created today. Process is more interesting than product."}],
    [{t:"Apply a creative constraint",dur:"15 min",desc:"Create with a rule: only 3 colors, exactly 50 words, 4 ingredients. Constraints spark creativity."},
     {t:"Combine two unrelated things",dur:"10 min",desc:"Pick two random objects or concepts. Create something that connects them. This is how innovation works."},
     {t:"Teach a creative skill",dur:"15 min",desc:"Show someone how to do something creative you know. Teaching deepens your own understanding."},
     {t:"Plan a creative project",dur:"10 min",desc:"Outline a larger creative project you want to complete in the next month. Break it into weekly milestones."}],
    [{t:"Work on your project",dur:"30 min",desc:"Spend 30 minutes on your larger creative project. Progress, not perfection."},
     {t:"Get feedback",dur:"10 min",desc:"Show your in-progress work to someone. Ask: what do you notice? What is unclear? What do you like?"},
     {t:"Finish and ship",dur:"15 min",desc:"Complete one creative piece and share it publicly. A blog post, an Instagram photo, a recipe. Launch it."},
     {t:"Celebrate creating",dur:"5 min",desc:"Look back at everything you created in 4 weeks. You went from 'I am not creative' to having a portfolio."}],
  ],
  "space": [
    [{t:"Friction mapping",dur:"15 min",desc:"Walk through your home and workspace. Where do you get stuck, frustrated, or lose things? List every friction point."},
     {t:"Goal-environment alignment",dur:"10 min",desc:"For each of your current goals, ask: does my space support or hinder this? Write specific conflicts."},
     {t:"One-touch rule",dur:"All day",desc:"When you pick something up, put it in its final place. No piles, no 'I will deal with it later.'"},
     {t:"Photograph your spaces",dur:"5 min",desc:"Take photos of your desk, kitchen counter, and bedroom. Fresh eyes reveal what you have normalized."}],
    [{t:"Workspace redesign",dur:"30 min",desc:"Clear your desk completely. Put back only what you use daily. Everything else gets a home elsewhere."},
     {t:"Create a focus zone",dur:"15 min",desc:"Designate one spot for deep work. Remove everything that does not serve concentration."},
     {t:"Optimize your digital space",dur:"15 min",desc:"Clean your desktop, organize your most-used apps, close old tabs. Digital clutter is still clutter."},
     {t:"Test your setup",dur:"All day",desc:"Work in your redesigned space for a full day. Note what works and what still needs adjusting."}],
    [{t:"Kitchen and morning routine zone",dur:"30 min",desc:"Organize your kitchen so healthy food prep is easy. Lay out tomorrow's clothes tonight."},
     {t:"Bedroom sleep optimization",dur:"15 min",desc:"Remove screens, add blackout solutions, declutter surfaces. Your bedroom should signal rest."},
     {t:"Entry/exit zones",dur:"15 min",desc:"Create a launch pad by your door: keys, wallet, bag. Never search for essentials again."},
     {t:"Review and celebrate",dur:"10 min",desc:"Compare your before photos to now. Write about how your redesigned spaces make you feel."}],
  ],
};
